#!/bin/bash
# deb2rpm: uses autobuild processes to convert a package with given ab files
##@license GPL-2.0+
# TODO: extra the info from control
# SYNOPSIS: 
# autobuild deb2rpm
. $AB/proc/10-defines.sh
mkdir $PKGNAME_${PKGVER}-${PKGREL}
tar xvf $PKGNAME_${PKGVER}-${PKGREL}.tar.xz -C $1
dpkg -x $PKGNAME_${PKGVER}-${PKGREL}.deb $PKGNAME_${PKGVER}-${PKGREL}/abdist
dpkg -e $PKGNAME_${PKGVER}-${PKGREL}.deb $PKGNAME_${PKGVER}-${PKGREL}/abdist/DEBIAN
pushd $PKGNAME_${PKGVER}-${PKGREL}
ln -s ../autobuild autobuild
. $AB/rpm/pack
