#! /bin/bash
# SYNOPSIS:
#+autobuild verconv
. $AB/ab3.sh plugin

# Test the versions
ignorant=false
deaf=false
ab2file(){
	if [ -e autobuild/overrides ]; then
		abinfo "autobuild/overrides found — you are facing an archive that is partly version 3."
		if [ -e autobuild/override ]; then
			abwarn 'autobuild/override not found — ab3-specific hack or something else?'
			deaf || return 2
		fi
		ignorant || return 1
	fi
	for i in postinst prerm postrm preinst; do
		if [ -e "$i" ]; then
			abinfo "Partly ab3 — found $i"
			if ! [ -e autobuild/override/DEBIAN/$i ]; then
		        
		fi
	done
return 0
}
