#!/bin/bash
# abrepoarchive: default autobuild settings for os3-repo archiving
# THIS SCRIPT IS INTENDED FOR USE INSIDE AUTOBUILD, WITH EXPORTED VATIABLES, LIKE AB, ARCH.
# SYNTAX: autobuild abrepoarchive PKGNAME PKGVER PKGREL
# CURRENTLY DEFINED PKGMGRs: dpkg, rpm.

# Useful for OS3 layout.
SORT=1; NAME_PREFIX="os3-"

# Directory Tree with priorities.
DIR_TREE="a b c d e f g h i j k m n o p q r s t u v w x y z 
	liba libb libc libd libe libf libg libh libi libj libk libl libm libn libo 
	libp libq libr libs libt libu libv libw libx liby libz l 0 1 2 3 4 5 6 7 8 9 _UNSORTED"

TREE=1
if [ "$CROSS" ] ; then
	TARGET_DIR=/os3-build-$CROSS
else
	TARGET_DIR=/os3-build
fi

# Functions, etc. ABSET, AB as exported by autobuild. ARCH as exported.
. $AB/lib/base.sh

# ARCH Translation for older versions of ab. Going to use x86_64 as main arch name instead of amd64. (Future pacman compatibility)
[ "$ARCH" == amd64 ] && ARCH=x86_64
prefixprint(){ [ "$SORT" == 1 ] && echo -ne "$NAME_PREFIX$1"; }
mvln(){ mv "$1" "$2" || aberr "Move from [$1] to [$2] failed."; ln -s "$2" "$1" || aberr "Link from [$1] to [$2] failed."; }

# regex match
if [ "$TREE" == 1 ];
then
	for _layout in $DIR_TREE; do [[ $1 =~ ^$_layout ]] && break; done || abwarn "$1 NOT SORTED"
else 
	abinfo "Not using an alphabetical tree."
fi

# in place
if [ "$SORT" == 1 ]; then
	mkdir -p $TARGET_DIR/os3-{ab,dpkg,rpm}/$_layout
else
	mkdir -p $TARGET_DIR/$_layout
fi

cp $1_$2-$3*.tar.xz $TARGET_DIR/$(prefixprint ab)/$_layout
cp $1_$2-$3*.deb $TARGET_DIR/$(prefixprint dpkg)/$_layout
cp /root/rpmbuild/RPMS/${ARCH}/$1-$2-$3.${ARCH}.rpm $TARGET_DIR/$(prefixprint rpm)/$_layout
abinfo "abRepoArchive done."

