#!/bin/bash
# autobuild-2to3: Convert autobuild2 to autobuild3 files
##@license GPL-2.0+
# SYNOPSIS:
#+autobuild verconv
. $AB/ab3.sh plugin

# Test the versions
brave=0 # Ignorance is strength!
deaf=0
ab2file(){
	if [ -e autobuild/overrides ]; then
		abinfo "autobuild/overrides found — you are facing an archive that is partly version 3."
		if [ -e autobuild/override ]; then
			abwarn 'autobuild/override not found — ab3-specific hack or something else?'
			((deaf)) || return 2
		fi
		((brave)) || return 1
	fi
	for i in postinst prerm postrm preinst; do
		if [ -e "$i" ]; then
			abinfo "Partly ab3 — found $i"
			if ! [ -e autobuild/override/DEBIAN/$i ]; then
				
			fi
		fi
	done
	return 0
}
