#! /bin/bash
export ABSET=/etc/autobuild
export AB=`cat /etc/autobuild/prefix`
# It's a pity that I hardcoded it.
# No worries man... use /etc
. $AB/lib/base.sh
for i in $AB/proc/*.sh
do
	if(. $i); then
		echo -e "\e[32m$i is running SUCCESS!\e[m"
	else
		echo -e "\e[31mERROR occurs when running $i. Read the message above.\e[m"
	fi
done
