#! /bin/bash
export ABSET=/etc/autobuild
export AB=$(cat /etc/autobuild/prefix || echo $(dirname $(dirname $0)))
# It's a pity that I hardcoded it.
# No worries man... use /etc
. $AB/lib/base.sh
. $AB/proc/*.sh