#! /bin/bash
eval unset $_ab_pm
PM_ALT=0 VER_S=' ' VER_E=''
abtrycom rpmarch || . "$ABLE/rpm/lib.sh" || rpmarch(){ echo "$1"; }

# Pre-RPM payload scripts
if [ -f autobuild/pre-rpm ]; then 
	. autobuild/pre-rpm
fi

# Optional Tag: tagname pkgs
rpmopttag(){
	[ "$2" ] || return
	echo -e "$1\t\t"; shift
	VER_NONE=1 depcom "$@"
}

# Fscked-up varname.
rpmreqprov(){
	if bool $ABRPMAUTOPROVONLY; then
  		echo "Autoprov:		yes"
  		echo "Autoreq:		no"
	else
  		echo "Autoreqprov:		yes"
	fi
}

# There should NOT be any errors.
rpmscripts(){
	for i in {pre,post}{inst,rm}; do
		i=${i/rm/un}
		echo "%${i%inst} -p /bin/bash"
		cat abscripts/$i
		echo
	done
}

# Files, list, boom!
# We are not going to meet any DEBIAN stuffs. The PAKMGR spec says that
# every support wipes its own butt.
rpmfiles(){
	find $PKGDIR | while read i; do
    	[[ -d "$i" && ! -L "$i" ]] && continue 
    	# echo "$i" >&2
    	grep "^$i\$" "$SRCDIR/autobuild/conffiles" && echo "%config"
   		echo "%defattr($(stat --printf %a,%U,%G "$i"),-)"
		# If there is a space, double quote!
		[[ $i =~ ' ' ]] && echo -n \"
    	echo -n /
    	printf %s "$(echo $i | cut -c 8-)"
		[[ $i =~ ' ' ]] && echo -n \"
    	echo
  	done
}

# RPM spec generation.
cat > abspec << _ab_rpm_endspec
# Generated automatically by autobuild on $(LANG=C date)
# This is made to ask rpm to pack from built binary.
Name:		$PKGNAME
Version:	${PKGVER//-/_}
Release:	$PKGREL
Epoch:		$PKGEPOCH
Summary:	$PKGDES

Group:		$(sed -f $ABLE/supp/rpm-sec <<< "$PKGSEC")
License:	Unknown
URL:		Unknown
$(rpmreqprov)
BuildRoot:	%{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Requires:	$(depcom $PKGDEP)
$(rpmopttag Conflicts $PKGCONFL)
$(rpmopttag Replaces $PKGREP)
$(rpmopttag Provides $PKGPROV)

%description
$PKGDES

%prep
true

%build
true

%install
rm -rf $RPM_BUILD_ROOT
cp -ra --reflink -l $PKGDIR $RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT

$(rpmscripts)

$(rpmfiles)
_ab_rpm_endspec

genspec > abspec
rpmbuild $([ "$CROSS" ] && rpmarch $CROSS) -bb abspec || aberr "RPM PACKING FAILED."
if [ -f autobuild/post-rpm ] ; then
	. autobuild/post-rpm
fi
eval unset $_ab_pm
