#!/bin/bash
##rpm/install: Procedure to install RPM stuffs
##@copyright GPL-2.0+
rpm_install_globbed=("/root/rpmbuild/RPMS/${rpm_arch_host}/$PKGNAME-$PKGVER-$PKGREL"*.rpm)
rpm "${PM_ROOTPARAM[@]}" -Uvh "${rpm_install_globbed[-1]}"
